//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Import.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到货.
        /// </summary>
        internal static string Delived {
            get {
                return ResourceManager.GetString("Delived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到货情况.
        /// </summary>
        internal static string DeliverCase {
            get {
                return ResourceManager.GetString("DeliverCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 因串件到货.
        /// </summary>
        internal static string DeliveredByBorrow {
            get {
                return ResourceManager.GetString("DeliveredByBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到货情况输入错误，请输入下面值中的一个:&quot;到货&quot;,&quot;未到货&quot;,&quot;因串件到货&quot;,&quot;被串件未到货&quot;.
        /// </summary>
        internal static string InputwrongForDeliver {
            get {
                return ResourceManager.GetString("InputwrongForDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未到货.
        /// </summary>
        internal static string NotDeliver {
            get {
                return ResourceManager.GetString("NotDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被串件未到货.
        /// </summary>
        internal static string NotDeliverByBorrow {
            get {
                return ResourceManager.GetString("NotDeliverByBorrow", resourceCulture);
            }
        }
    }
}
